version: "2"

services:

  php70-minimal:
    container_name: php70-minimal
    build:
      dockerfile: Dockerfile.7.0-min
      context: .
    volumes:
      - "./scripts:/srv"

  php70-complete:
    container_name: php70-complete
    build:
      dockerfile: Dockerfile.7.0
      context: .
    volumes:
      - "./scripts:/srv"

  php71-minimal:
    container_name: php71-minimal
    build:
      dockerfile: Dockerfile.7.1-min
      context: .
    volumes:
      - "./scripts:/srv"

  php71-complete:
    container_name: php71-complete
    build:
      dockerfile: Dockerfile.7.1
      context: .
    volumes:
      - "./scripts:/srv"

  php72-minimal:
    container_name: php72-minimal
    build:
      dockerfile: Dockerfile.7.2-min
      context: .
    volumes:
      - "./scripts:/srv"

  php72-complete:
    container_name: php72-complete
    build:
      dockerfile: Dockerfile.7.2
      context: .
    volumes:
      - "./scripts:/srv"
