version: "2"
services:
  benchmark:
    container_name: phpbenchmark
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/srv"