version: "2"

services:

  '5.6-alpine':
    container_name: php56-alpine
    environment:
      - CONTAINER_NAME=56-alpine
    build:
      dockerfile: Dockerfile-56-alpine
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '5.6-alpine-skratch':
    container_name: php56-alpine-skratch
    environment:
      - CONTAINER_NAME=56-alpine-skratch
    build:
      dockerfile: Dockerfile-56-alpine-skratch
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '5.6-debian':
    container_name: php56-debian
    environment:
      - CONTAINER_NAME=56-debian
    build:
      dockerfile: Dockerfile-56-debian
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"
  
  '5.6-debian-skratch':
    container_name: php56-debian-skratch
    environment:
      - CONTAINER_NAME=56-debian-skratch
    build:
      dockerfile: Dockerfile-56-debian-skratch
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '5.6-ubuntu':
    container_name: php56-ubuntu
    environment:
      - CONTAINER_NAME=56-ubuntu
    build:
      dockerfile: Dockerfile-56-ubuntu
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0':
    container_name: php70
    environment:
      - CONTAINER_NAME=70-complete
    build:
      dockerfile: Dockerfile-70
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-min':
    container_name: php70-min
    environment:
      - CONTAINER_NAME=70-minimal
    build:
      dockerfile: Dockerfile-70-min
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-min.quick':
    container_name: php70-min-quick
    environment:
      - CONTAINER_NAME=70-minimal
    build:
      dockerfile: Dockerfile-70-min
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"
    command: bash /opt/benchmark -quick
    
  '7.0-alpine':
    container_name: php70-alpine
    environment:
      - CONTAINER_NAME=70-alpine
    build:
      dockerfile: Dockerfile-70-alpine
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-alpine-skratch':
    container_name: php70-alpine-skratch
    environment:
      - CONTAINER_NAME=70-alpine-skratch
    build:
      dockerfile: Dockerfile-70-alpine-skratch
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-debian':
    container_name: "70-debian"
    environment:
      - CONTAINER_NAME=70-debian
    build:
      dockerfile: Dockerfile-70-debian
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-debian-skratch':
    container_name: php70-debian-skratch
    environment:
      - CONTAINER_NAME=70-debian-skratch
    build:
      dockerfile: Dockerfile-70-debian-skratch
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-ubuntu':
    container_name: php70-ubuntu
    environment:
      - CONTAINER_NAME=70-ubuntu
    build:
      dockerfile: Dockerfile-70-ubuntu
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-ext-static':
    container_name: php70-ext-static
    environment:
      - CONTAINER_NAME=70-ext-static
    build:
      dockerfile: Dockerfile-70-ext-static
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.0-ext-dynamic':
    container_name: php70-ext-dynamic
    environment:
      - CONTAINER_NAME=70-ext-dynamic
    build:
      dockerfile: Dockerfile-70-ext-dynamic
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.1':
    container_name: php71
    environment:
      - CONTAINER_NAME=71-complete
    build:
      dockerfile: Dockerfile-71
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.1-min':
    container_name: php71-min
    environment:
      - CONTAINER_NAME=71-minimal
    build:
      dockerfile: Dockerfile-71-min
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.1-alpine':
    container_name: "71-alpine"
    environment:
      - CONTAINER_NAME=71-alpine
    build:
      dockerfile: Dockerfile-71-alpine
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.1-alpine-skratch':
    container_name: php71-alpine-skratch
    environment:
      - CONTAINER_NAME=71-alpine-skratch
    build:
      dockerfile: Dockerfile-71-alpine-skratch
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.1-debian':
    container_name: php71-debian
    environment:
      - CONTAINER_NAME=71-debian
    build:
      dockerfile: Dockerfile-71-debian
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.1-debian-skratch':
    container_name: php71-debian-skratch
    environment:
      - CONTAINER_NAME=71-debian-skratch
    build:
      dockerfile: Dockerfile-71-debian-skratch
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.1-ubuntu':
    container_name: php71-ubuntu
    environment:
      - CONTAINER_NAME=71-ubuntu
    build:
      dockerfile: Dockerfile-71-ubuntu
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.2':
    container_name: php72
    environment:
      - CONTAINER_NAME=72-complete
    build:
      dockerfile: Dockerfile-72
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.2-min':
    container_name: php72-minimal
    environment:
      - CONTAINER_NAME=72-minimal
    build:
      dockerfile: Dockerfile-72-min
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.2-alpine':
    container_name: php72-alpine
    environment:
      - CONTAINER_NAME=72-alpine
    build:
      dockerfile: Dockerfile-72-alpine
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

  '7.2-debian':
    container_name: php72-debian
    environment:
      - CONTAINER_NAME=72-debian
    build:
      dockerfile: Dockerfile-72-debian
      context: .
    volumes:
      - "./bin:/opt"
      - "./scripts:/srv"
      - "./output:/out"
      - "./temp:/tmp"

