version: "2"

services:

  php70-minimal:
    container_name: php70-minimal
    build:
      dockerfile: Dockerfile-70-min
      context: .
    volumes:
      - "./scripts:/srv"

  php70-complete:
    container_name: php70-complete
    build:
      dockerfile: Dockerfile-70
      context: .
    volumes:
      - "./scripts:/srv"

  php71-minimal:
    container_name: php71-minimal
    build:
      dockerfile: Dockerfile-71-min
      context: .
    volumes:
      - "./scripts:/srv"

  php71-complete:
    container_name: php71-complete
    build:
      dockerfile: Dockerfile-71
      context: .
    volumes:
      - "./scripts:/srv"

  php72-minimal:
    container_name: php72-minimal
    build:
      dockerfile: Dockerfile-72-min
      context: .
    volumes:
      - "./scripts:/srv"

  php72-complete:
    container_name: php72-complete
    build:
      dockerfile: Dockerfile-72
      context: .
    volumes:
      - "./scripts:/srv"
